### ISSUE TITLE
endgame stats don't get sent

### ISSUE THREAD

**Issue by andrewzah** [sauerbraten/waiter#1]
I think it comes down to [this logic check](https://github.com/sauerbraten/waiter/blob/master/pkg/server/server.go#L286):

```go
if _, ok := s.StatsServer.(*mserver.StatsClient); ok {
    s.ReportEndgameStats()
}
```
Removing that check and just calling `s.ReportEndgameStats()` appears to work.

**Comment by sauerbraten** [comment]
Good find! I fixed this in https://github.com/sauerbraten/maitred/commit/5b5d626a6e8f2a1a5c7ae70a7849faf16ba2c578, then vendored the changes into waiter and adapted to the new API: https://github.com/sauerbraten/waiter/commit/62548380766116a5184cd933ba936cf58c9fd61d
